# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests and Auto-Revert

on:
  push:
    branches: ["main"]

permissions:
  contents: "write"
  pull-requests: "write"
  workflows: "write" # needed ?

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 ## needed ?
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run vitest
        run: pnpm test
        continue-on-error: true
        id: test-step

      - name: Auto-Revert if tests failed
        if: steps.test-step.outcome == 'failure'
        run: |
          set -x  # Turn on debug mode

          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Get commit data
          TRIGGER_COMMIT="${{ github.sha }}"
          echo "Trigger commit: $TRIGGER_COMMIT"

          # Get the PR data
          PR_INFO=$(gh pr list --search "$TRIGGER_COMMIT" --state merged --json number,author --jq '.[0] | {number: .number, author: .author.login}')
          if [ -z "$PR_INFO" ]; then
            echo "Could not find associated merged PR for commit $TRIGGER_COMMIT. Exiting."
            exit 1
          fi

          PR_NUMBER=$(echo $PR_INFO | jq -r '.number')
          PR_CREATOR=$(echo $PR_INFO | jq -r '.author')
          echo "PR number: $PR_NUMBER"
          echo "PR creator: $PR_CREATOR"

          # Step 1: Revert on main branch
          if git revert --no-edit $TRIGGER_COMMIT; then
            echo "Successfully reverted PR #$PR_NUMBER"
            git push origin main
          else
            echo "Failed to revert PR #$PR_NUMBER. Manual intervention may be required."
            exit 1
          fi

          # Step 2: Create a new branch
          REVERT_BRANCH="auto-revert-${PR_NUMBER}-$(date +%s)"
          git checkout -b $REVERT_BRANCH

          # Step 3: Revert the revert commit
          REVERT_COMMIT=$(git rev-parse HEAD)
          if git revert --no-edit $REVERT_COMMIT; then
            echo "Successfully reverted the revert commit on $REVERT_BRANCH"
            git push origin $REVERT_BRANCH
          else
            echo "Failed to revert the revert commit #$REVERT_COMMIT. Manual intervention may be required."
            exit 1
          fi

          # Step 4: Create a PR based on new branch
          NEW_PR_URL=$(gh pr create --base main --head $REVERT_BRANCH \
            --title "Fix: Revert PR #$PR_NUMBER due to failing tests" \
            --body "This PR was created to address the issues in the reverted PR #$PR_NUMBER.
            Please fix the failing tests and update this PR accordingly.

            Original PR: #$PR_NUMBER" \
            --assignee "$PR_CREATOR")

          echo "New PR URL: $NEW_PR_URL"

          # Step 5: Comment on the original PR
          gh pr comment $PR_NUMBER --body "This PR has been automatically reverted due to failing E2E tests.
          A new PR has been created to address the issues: $NEW_PR_URL" # tag @$PR_CREATOR on this comment too?
        env:
          GITHUB_TOKEN: ${{ github.token }}
