# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests and Auto-Revert

on:
  push:
    branches: ["main"]

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run vitest
        run: pnpm test
        continue-on-error: true
        id: test-step

      - name: Auto-Revert if tests failed
        if: steps.test-step.outcome == 'failure'
        run: |
          # Configure Git
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"

          # Get the PR number associated with the last push to main
          PR_NUMBER=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls --jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            echo "Could not find associated PR number. Exiting."
            exit 1
          fi

          echo "Associated PR number: $PR_NUMBER"

          # Attempt to revert the last commit
          if ! git revert ${{ github.sha }} -m 1; then
            echo "Revert failed due to conflicts. Please resolve manually."
            exit 1
          fi

          git push origin main

          # Reopen the PR with a comment
          gh pr reopen $PR_NUMBER -c "This PR has been automatically reopened due to failing tests.
          Please fix the failing tests and update this PR."
        env:
          GH_TOKEN: ${{ github.token }}
