# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run vitest
        run: pnpm test
