# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests and Auto-Revert

on:
  push:
    branches: ["main"]

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run vitest
        run: pnpm test
        continue-on-error: true
        id: test-step

      - name: Auto-Revert if tests failed
        if: steps.test-step.outcome == 'failure'
        run: |
          set -x  # Turn on debug mode

          # Ensure we're on the main branch
          git switch main

          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Get commit data
          TRIGGER_COMMIT="${{ github.sha }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"

          echo "Trigger commit: $TRIGGER_COMMIT"
          echo "Commit message: $COMMIT_MSG"

          # Get the PR number associated with the last push to main
          PR_NUMBER=$(gh api repos/${{ github.repository }}/commits/$TRIGGER_COMMIT/pulls --jq '.[0].number')
          if [ -z "$PR_NUMBER" ]; then
            echo "Could not find associated PR number. Exiting."
            exit 1
          fi

          echo "PR number: $PR_NUMBER"

          # Get the original PR creator
          PR_CREATOR=$(gh pr view $PR_NUMBER --json author -q .author.login)

          # Create a new branch for the fix
          REVERT_BRANCH="auto-revert-${PR_NUMBER}-$(date +%s)"
          git switch -c $REVERT_BRANCH
          git push origin $REVERT_BRANCH

          # Revert the squashed and merged commit
          git switch main
          if git revert --no-edit $TRIGGER_COMMIT; then
            echo "Successfully reverted PR #$PR_NUMBER"
            git commit --amend -m "[REVERT] $COMMIT_MSG"
            git push origin main
          else
            echo "Failed to revert PR #$PR_NUMBER. Manual intervention may be required."
            exit 1
          fi

          # Create a new PR
          NEW_PR_URL=$(gh pr create --base main --head $REVERT_BRANCH \
            --title "Fix: Revert PR #$PR_NUMBER due to failing tests" \
            --body "This PR was created to address the issues in the reverted PR #$PR_NUMBER.
            Please fix the failing tests and update this PR accordingly.

            Original PR: #$PR_NUMBER" \
            --assignee "$PR_CREATOR")

          # Comment on the original PR
          gh pr comment $PR_NUMBER --body "This PR has been automatically reverted due to failing E2E tests.
          A new PR has been created to address the issues: $NEW_PR_URL" # tag @$PR_CREATOR on this comment too?
        env:
          GITHUB_TOKEN: ${{ github.token }}
